<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-FinkiBets-6d6a5d56-cbaf-4421-b66f-ead649985925</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.23" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.23" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.23" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.23" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.23" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.23" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.23" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.23" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FinkiBets.Domain\FinkiBets.Domain.csproj" />
    <ProjectReference Include="..\FinkiBets.Repository\FinkiBets.Repository.csproj" />
    <ProjectReference Include="..\FinkiBets.Service\FinkiBets.Service.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\" />
  </ItemGroup>

</Project>
